version: '3.8'

services:

  graffiti-tracker:
    container_name: graffiti-tracker
    build: app
    volumes:
      - ./app:/mount/app
    depends_on:
      - mongo
    ports:
      - 8000:8000

  mongo:
    image: mongo:6.0.6
    container_name: graffiti-mongo
    restart: always
    command: "--bind_ip_all --replSet rs0"
    volumes:
      - ./config/mongo:/docker-entrypoint-initdb.d/
    extra_hosts:
      - "mongo:127.0.0.1"
